import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import './globals.css';


export const metadata = {
  title: 'Simple API',
  description: 'Simple API, Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-slate-800">
        <Navbar />
        <div className='iframe-bar max-w-3xl mx-auto p-3 py-32 min-h-screen'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
